package com.deplink.homegenius.constant;

/**
 * Created by Administrator on 2017/12/19.
 */
public class AirKeyNameConstant {
    public interface KEYNAME{
        int KEYNAME_POWER_OPEN = 99;
        int KEYNAME_POWER_CLOSE = 100;
        int KEYNAME_WIND_AUTO = 102;
        int KEYNAME_WIND_LOW = 103;
        int KEYNAME_WIND_MIDDLE = 104;
        int KEYNAME_WIND_HIGH = 105;
        int KEYNAME_WIND_DIRECTION_UP = 106;
        int KEYNAME_WIND_DIRECTION_MIDDLE = 107;
        int KEYNAME_WIND_DIRECTION_DOWN = 108;
        int KEYNAME_WIND_DIRECTION_AUTO = 109;
        int KEYNAME_MODE_AUTO = 111;
        int KEYNAME_MODE_COLD = 112;
        int KEYNAME_MODE_DEHUMIT = 113;
        int KEYNAME_MODE_WIND = 114;
        int KEYNAME_MODE_HOT = 115;

        int KEYNAME_TEMPTURE_HOT_16 = 216;
        int KEYNAME_TEMPTURE_HOT_17 = 217;
        int KEYNAME_TEMPTURE_HOT_18 = 218;
        int KEYNAME_TEMPTURE_HOT_19 = 219;
        int KEYNAME_TEMPTURE_HOT_20 = 220;
        int KEYNAME_TEMPTURE_HOT_21 = 221;
        int KEYNAME_TEMPTURE_HOT_22 = 222;
        int KEYNAME_TEMPTURE_HOT_23 = 223;
        int KEYNAME_TEMPTURE_HOT_24 = 224;
        int KEYNAME_TEMPTURE_HOT_25 = 225;
        int KEYNAME_TEMPTURE_HOT_26 = 226;
        int KEYNAME_TEMPTURE_HOT_27 = 227;
        int KEYNAME_TEMPTURE_HOT_28 = 228;
        int KEYNAME_TEMPTURE_HOT_29 = 229;
        int KEYNAME_TEMPTURE_HOT_30 = 230;
        int KEYNAME_TEMPTURE_COLD_16 = 116;
        int KEYNAME_TEMPTURE_COLD_17 = 117;
        int KEYNAME_TEMPTURE_COLD_18 = 118;
        int KEYNAME_TEMPTURE_COLD_19 = 119;
        int KEYNAME_TEMPTURE_COLD_20 = 120;
        int KEYNAME_TEMPTURE_COLD_21 = 121;
        int KEYNAME_TEMPTURE_COLD_22 = 122;
        int KEYNAME_TEMPTURE_COLD_23 = 123;
        int KEYNAME_TEMPTURE_COLD_24 = 124;
        int KEYNAME_TEMPTURE_COLD_25 = 125;
        int KEYNAME_TEMPTURE_COLD_26 = 126;
        int KEYNAME_TEMPTURE_COLD_27 = 127;
        int KEYNAME_TEMPTURE_COLD_28 = 128;
        int KEYNAME_TEMPTURE_COLD_29 = 129;
        int KEYNAME_TEMPTURE_COLD_30 = 130;

    }
}
